/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
export enum QUALITY {
  DECREASE_BEFORE_SELL_DATE = 1,
  DECREASE_AFTER_SELL_DATE = 2,
  INCREASE_BEFORE_SELL_DATE = 1,
  INCREASE_AFTER_SELL_DATE = 2,

  SMELLY_ITEM_DECREASE_BEFORE_SELL_DATE = 2,
  SMELLY_ITEM_DECREASE_AFTER_SELL_DATE = 4,

  BACKSTAGE_PASS_INCREASE_DEFAULT = 1,
  BACKSTAGE_PASS_INCREASE_LESS_THAN_10_DAYS = 2,
  BACKSTAGE_PASS_INCREASE_LESS_THAN_5_DAYS = 3,

  MINIMUM_QUALITY_ITEM = 0,
  MAXIMUM_QUALITY_ITEM = 50,
  MAXIMUM_QUALITY_LEGENDARY_ITEM = 80,
}
